#!/usr/bin/env ruby
message_file = ARGV[0]
message = File.read(message_file)

$regex = /(feat|fix|update|dev|doc):.*/

if !$regex.match(message)
  puts "[POLICY] Your message is not formatted correctly"
  exit 1
end


# 안씀. 그냥 단순 저장해둔 파일임