#!/bin/bash

message_file="$1" 
message=$(cat "$message_file")

COMMITFORMAT="(feat|fix|update|dev|doc)"
default_pattern="^($COMMITFORMAT: )"


if [[ ! $message =~ $default_pattern ]]; then
  echo '🚨 Git 컨벤션을 준수해주세요! 👮'
  echo ''
  echo '🏃      🚓💨💨'
  osascript -e 'display notification "🚨 Git 컨벤션을 준수해주세요! 👮" with title "컨벤션 경고"'
  exit 1
fi

exit 0